/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * File: physics.c
 *
 * Code generated for Simulink model 'fast'.
 *
 * Model version                  : 1.243
 * Simulink Coder version         : 9.2 (R2019b) 18-Jul-2019
 * C/C++ source code generated on : Tue Dec 31 19:37:27 2019
 *
 * Target selection: ert.tlc
 * Embedded hardware selection: Intel->x86-64 (Linux 64)
 * Code generation objectives:
 *    1. Execution efficiency
 *    2. Debugging
 *    3. Traceability
 * Validation result: All passed
 */

#include "physics.h"

/* Include model header file for global data */
//#include "matlab.h"


// 		SCRITTO DA PEPO 	//
extern DW_fast_T fast_DW;
// 	FINE SCRITTO DA PEPO 	//


/* System initialize for atomic system: '<Root>/Physics' */
void physics_Init(void)
{
  /* InitializeConditions for Delay: '<S7>/Delay' */
  fast_DW.Delay_DSTATE[0] = 0.0F;
  fast_DW.Delay_DSTATE[1] = 3.14159274F;
  fast_DW.Delay_DSTATE[2] = 0.0F;
  fast_DW.Delay_DSTATE[3] = 0.0F;

  /* InitializeConditions for DiscreteIntegrator: '<S7>/Discrete-Time Integrator' */
  fast_DW.DiscreteTimeIntegrator_DSTATE[0] = 0.0F;
  fast_DW.DiscreteTimeIntegrator_DSTATE[1] = 3.14159274F;
  fast_DW.DiscreteTimeIntegrator_DSTATE[2] = 0.0F;
  fast_DW.DiscreteTimeIntegrator_DSTATE[3] = 0.0F;
}

/* Output and update for atomic system: '<Root>/Physics' */
void physics(uint16_T rtu_CCR, real32_T rtu_dist, const real32_T rtu_noise[2],
             uint16_T rtyy_CNT_alphaCNT_theta[2])
{
  /* local block i/o variables */
  real32_T rtb_Sum1;
  real32_T rtb_current;
  boolean_T rEQ0;
  real32_T q;
  real32_T rtb_bemf;
  real32_T b_x_tmp;
  real32_T rtb_TmpSignalConversionAtSFun_0;
  real32_T rtb_TmpSignalConversionAtSFun_1;
  real32_T rtb_q_d_idx_0;
  real32_T rtb_q_d_idx_1;
  real32_T rtb_q_d_idx_2;
  real32_T q_idx_2;
  real32_T q_idx_3;
  real32_T rtb_q_d_idx_2_tmp;
  real32_T rtb_q_d_idx_2_tmp_0;
  real32_T rtb_q_d_idx_2_tmp_1;

  /* Delay: '<S3>/Delay' */
  /* MATLAB Function 'Physics/Physics/Disturbance_generator/dist_gen': '<S8>:1' */
  /* '<S8>:1:3' tau_1 = F*Larm; */
  /* '<S8>:1:4' tau_2 = F*Lp; */
  rtb_current = fast_DW.Delay_DSTATE_p;

  /* Gain: '<S3>/Gain2' */
  rtb_bemf = 0.5376F * rtb_current;

  /* DataTypeConversion: '<S6>/Cast1' */
  rtb_current = rtu_CCR;

  /* Sum: '<S3>/Sum1' incorporates:
   *  Fcn: '<S6>/Fcn1'
   */
  rtb_Sum1 = (2.0F * rtb_current / 5250.0F - 1.0F) * 6.0F - rtb_bemf;

  /* DiscreteStateSpace: '<S3>/Discrete State-Space' */
  {
    rtb_current = 1.0F*fast_DW.DiscreteStateSpace_DSTATE;
    rtb_current += 0.161290318F*rtb_Sum1;
  }

  /* SignalConversion generated from: '<S10>/ SFunction ' incorporates:
   *  Gain: '<S3>/Gain3'
   *  MATLAB Function: '<S4>/dist_gen'
   *  MATLAB Function: '<S7>/f_mecc'
   *  Sum: '<S7>/Sum2'
   */
  rtb_TmpSignalConversionAtSFun_0 = 0.48384F * rtb_current + rtu_dist * 0.216F;
  rtb_TmpSignalConversionAtSFun_1 = rtu_dist * 0.337F;

  /* MATLAB Function: '<S7>/f_mecc' incorporates:
   *  Delay: '<S7>/Delay'
   */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     09-Dec-2019 19:45:31 */
  /* MATLAB Function 'Physics/Physics/Pendulum/f_mecc': '<S10>:1' */
  /* '<S10>:1:7' al_d = q(3); */
  /* '<S10>:1:8' tau1 = tau(1); */
  /* '<S10>:1:9' tau2 = tau(2); */
  /* '<S10>:1:10' th = q(2); */
  /* '<S10>:1:11' th_d = q(4); */
  /* '<S10>:1:12' q_d = [al_d;th_d;((Jp.*tau1.*-2.0+Jp.*al_d.*bma.*2.0+Jp.^2.*al_d.*th_d.*sin(th.*2.0).*2.0+Larm.*lp.*mp.*tau2.*cos(th).*2.0-Larm.*bp.*lp.*mp.*th_d.*cos(th).*2.0+Larm.*g.*lp.^2.*mp.^2.*cos(th).*sin(th).*2.0-Jp.*Larm.*lp.*mp.*th_d.^2.*sin(th).*2.0+Jp.*Larm.*al_d.^2.*lp.*mp.*sin(th.*2.0).*cos(th)).*(-1.0./2.0))./(Jp.^2.*sin(th).^2+J0.*Jp-Larm.^2.*lp.^2.*mp.^2.*cos(th).^2);(J0.*tau2.*2.0+Jp.*tau2.*sin(th).^2.*2.0-J0.*bp.*th_d.*2.0+Jp.^2.*al_d.^2.*sin(th.*2.0).*sin(th).^2-Jp.*bp.*th_d.*sin(th).^2.*2.0+J0.*Jp.*al_d.^2.*sin(th.*2.0)+Jp.*g.*lp.*mp.*sin(th).^3.*2.0-Larm.*lp.*mp.*tau1.*cos(th).*2.0+J0.*g.*lp.*mp.*sin(th).*2.0+Larm.*al_d.*bma.*lp.*mp.*cos(th).*2.0-Larm.^2.*lp.^2.*mp.^2.*th_d.^2.*cos(th).*sin(th).*2.0+Jp.*Larm.*al_d.*lp.*mp.*th_d.*sin(th.*2.0).*cos(th).*2.0)./(Jp.^2.*sin(th).^2.*2.0+J0.*Jp.*2.0-Larm.^2.*lp.^2.*mp.^2.*cos(th).^2.*2.0)]; */
  rtb_bemf = sinf(fast_DW.Delay_DSTATE[1]);
  b_x_tmp = cosf(fast_DW.Delay_DSTATE[1]);
  q = sinf(fast_DW.Delay_DSTATE[1] * 2.0F);
  rtb_q_d_idx_0 = fast_DW.Delay_DSTATE[2];
  rtb_q_d_idx_1 = fast_DW.Delay_DSTATE[3];
  q_idx_2 = rtb_bemf * rtb_bemf;
  q_idx_3 = fast_DW.Delay_DSTATE[2] * fast_DW.Delay_DSTATE[2];
  rtb_q_d_idx_2_tmp = fast_DW.Delay_DSTATE[3] * fast_DW.Delay_DSTATE[3];
  rtb_q_d_idx_2_tmp_0 = q_idx_2 * 1.84098662E-5F;
  rtb_q_d_idx_2_tmp_1 = b_x_tmp * b_x_tmp * 1.83131979E-5F;
  rtb_q_d_idx_2 = (((((((0.00429067202F * fast_DW.Delay_DSTATE[2] * 0.0174F *
    2.0F + 0.00429067202F * rtb_TmpSignalConversionAtSFun_0 * -2.0F) +
                        1.84098662E-5F * fast_DW.Delay_DSTATE[2] *
                        fast_DW.Delay_DSTATE[3] * q * 2.0F) + 0.00427939277F *
                       rtb_TmpSignalConversionAtSFun_1 * b_x_tmp * 2.0F) -
                      1.02705417E-5F * fast_DW.Delay_DSTATE[3] * b_x_tmp * 2.0F)
                     + 0.000831724377F * b_x_tmp * rtb_bemf * 2.0F) -
                    rtb_q_d_idx_2_tmp * 1.83614684E-5F * rtb_bemf * 2.0F) +
                   q_idx_3 * 0.000926785171F * 0.156F * 0.127F * q * b_x_tmp) *
    -0.5F / ((rtb_q_d_idx_2_tmp_0 + 4.49253384E-5F) - rtb_q_d_idx_2_tmp_1);
  rtb_bemf = (((((((((((0.00429067202F * rtb_TmpSignalConversionAtSFun_1 *
                        q_idx_2 * 2.0F + 0.0104704667F *
                        rtb_TmpSignalConversionAtSFun_1 * 2.0F) - 2.51291222E-5F
                       * fast_DW.Delay_DSTATE[3] * 2.0F) + q_idx_3 *
                      1.84098662E-5F * q * q_idx_2) - 1.02976137E-5F *
                     fast_DW.Delay_DSTATE[3] * q_idx_2 * 2.0F) + q_idx_3 *
                    4.49253384E-5F * q) + 0.000833916711F * powf(rtb_bemf, 3.0F)
                   * 2.0F) - 0.00427939277F * rtb_TmpSignalConversionAtSFun_0 *
                  b_x_tmp * 2.0F) + 0.00203499524F * rtb_bemf * 2.0F) + 0.216F *
                fast_DW.Delay_DSTATE[2] * 0.0174F * 0.156F * 0.127F * b_x_tmp *
                2.0F) - rtb_q_d_idx_2_tmp * 1.83131979E-5F * b_x_tmp * rtb_bemf *
               2.0F) + 0.000926785171F * fast_DW.Delay_DSTATE[2] * 0.156F *
              0.127F * fast_DW.Delay_DSTATE[3] * q * b_x_tmp * 2.0F) /
    ((rtb_q_d_idx_2_tmp_0 * 2.0F + 8.98506769E-5F) - rtb_q_d_idx_2_tmp_1 * 2.0F);

  /* DiscreteIntegrator: '<S7>/Discrete-Time Integrator' incorporates:
   *  Delay: '<S7>/Delay'
   *  MATLAB Function: '<S7>/f_mecc'
   */
  rtb_TmpSignalConversionAtSFun_0 = 5.0E-5F * fast_DW.Delay_DSTATE[2] +
    fast_DW.DiscreteTimeIntegrator_DSTATE[0];
  rtb_TmpSignalConversionAtSFun_1 = 5.0E-5F * fast_DW.Delay_DSTATE[3] +
    fast_DW.DiscreteTimeIntegrator_DSTATE[1];
  q_idx_2 = 5.0E-5F * rtb_q_d_idx_2 + fast_DW.DiscreteTimeIntegrator_DSTATE[2];
  q_idx_3 = 5.0E-5F * rtb_bemf + fast_DW.DiscreteTimeIntegrator_DSTATE[3];

  /* Sum: '<S2>/Sum3' */
  /* MATLAB Function 'Physics/Physics/Encoder/rad_to_CNT': '<S9>:1' */
  /* '<S9>:1:3' CNT = floor(encoder_res/(2*pi)*mod(rad,2*pi)); */
  rtb_q_d_idx_2_tmp = rtb_TmpSignalConversionAtSFun_0 + rtu_noise[0];

  /* MATLAB Function: '<S5>/rad_to_CNT' */
  if (rtb_q_d_idx_2_tmp == 0.0F) {
    b_x_tmp = 0.0F;
  } else {
    b_x_tmp = fmodf(rtb_q_d_idx_2_tmp, 6.28318548F);
    rEQ0 = (b_x_tmp == 0.0F);
    if (!rEQ0) {
      q = fabsf(rtb_q_d_idx_2_tmp / 6.28318548F);
      rEQ0 = (fabsf(q - floorf(q + 0.5F)) <= 1.1920929E-7F * q);
    }

    if (rEQ0) {
      b_x_tmp = 0.0F;
    } else {
      if (rtb_q_d_idx_2_tmp < 0.0F) {
        b_x_tmp += 6.28318548F;
      }
    }
  }

  /* DataTypeConversion: '<S5>/Cast2' incorporates:
   *  MATLAB Function: '<S5>/rad_to_CNT'
   */
  rtyy_CNT_alphaCNT_theta[0] = (uint16_T)floorf(651.898621F * b_x_tmp);

  /* Sum: '<S2>/Sum3' */
  rtb_q_d_idx_2_tmp = rtb_TmpSignalConversionAtSFun_1 + rtu_noise[1];

  /* MATLAB Function: '<S5>/rad_to_CNT' */
  if (rtb_q_d_idx_2_tmp == 0.0F) {
    b_x_tmp = 0.0F;
  } else {
    b_x_tmp = fmodf(rtb_q_d_idx_2_tmp, 6.28318548F);
    rEQ0 = (b_x_tmp == 0.0F);
    if (!rEQ0) {
      q = fabsf(rtb_q_d_idx_2_tmp / 6.28318548F);
      rEQ0 = (fabsf(q - floorf(q + 0.5F)) <= 1.1920929E-7F * q);
    }

    if (rEQ0) {
      b_x_tmp = 0.0F;
    } else {
      if (rtb_q_d_idx_2_tmp < 0.0F) {
        b_x_tmp += 6.28318548F;
      }
    }
  }

  /* DataTypeConversion: '<S5>/Cast2' incorporates:
   *  MATLAB Function: '<S5>/rad_to_CNT'
   */
  rtyy_CNT_alphaCNT_theta[1] = (uint16_T)floorf(651.898621F * b_x_tmp);

  /* Update for Delay: '<S7>/Delay' */
  fast_DW.Delay_DSTATE[0] = rtb_TmpSignalConversionAtSFun_0;
  fast_DW.Delay_DSTATE[1] = rtb_TmpSignalConversionAtSFun_1;
  fast_DW.Delay_DSTATE[2] = q_idx_2;
  fast_DW.Delay_DSTATE[3] = q_idx_3;

  /* Update for Delay: '<S3>/Delay' */
  fast_DW.Delay_DSTATE_p = q_idx_2;

  /* Update for DiscreteStateSpace: '<S3>/Discrete State-Space' */
  {
    real32_T xnew[1];
    xnew[0] = 0.161290333F*fast_DW.DiscreteStateSpace_DSTATE;
    xnew[0] += 0.187304884F*rtb_Sum1;
    (void) memcpy(&fast_DW.DiscreteStateSpace_DSTATE, xnew,
                  sizeof(real32_T)*1);
  }

  /* Update for DiscreteIntegrator: '<S7>/Discrete-Time Integrator' */
  fast_DW.DiscreteTimeIntegrator_DSTATE[0] = 5.0E-5F * rtb_q_d_idx_0 +
    rtb_TmpSignalConversionAtSFun_0;
  fast_DW.DiscreteTimeIntegrator_DSTATE[1] = 5.0E-5F * rtb_q_d_idx_1 +
    rtb_TmpSignalConversionAtSFun_1;
  fast_DW.DiscreteTimeIntegrator_DSTATE[2] = 5.0E-5F * rtb_q_d_idx_2 + q_idx_2;
  fast_DW.DiscreteTimeIntegrator_DSTATE[3] = 5.0E-5F * rtb_bemf + q_idx_3;
}

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
